### ISSUE TITLE
OSS?

### ISSUE THREAD

**Issue by mineek** [BenjaminHornbeck6/lemonra1n#1]
Are you gonna make it open source?

**Comment by BenjaminHornbeck6** [comment]
I don’t like to open source my work so no

**Comment by BenjaminHornbeck6** [comment]
Keeping my code away from one specific person if you think my application is doing anything malicious other than running unsigned executables and bootstrapping your device there are many reverse engineers

**Comment by mineek** [comment]
what do you mean by "Keeping my code away from one specific person"?

**Comment by itsnebulalol** [comment]
Since there is no license in Pogo, you do need to have permission. Even if there was a license, most licenses make it so you have to open source.

**Comment by BenjaminHornbeck6** [comment]
Ok, I’m removing lemonra1n helper until I get permission
