### ISSUE TITLE
For Linux Use Palera1n to Boot

### ISSUE THREAD

**Issue by pwnedcold** [BenjaminHornbeck6/lemonra1n#2]
yall who are on linux use palera1n to boot then install lemonra1n loader if you wish so

but it would be cool if you port the app to linux too

**Comment by BenjaminHornbeck6** [comment]
I don’t have a device running linux and I’ve only made apps for iOS, macOS and tvOS

**Comment by BenjaminHornbeck6** [comment]
I was replying to “but it would be cool if you port the app to linux too”
