### ISSUE TITLE
copy of pogo

### ISSUE THREAD

**Issue by pwnedcold** [BenjaminHornbeck6/lemonra1n#3]
my guy the loader its clearly a copy of pogo , either open source it or violating license

**Comment by BenjaminHornbeck6** [comment]
That’s correct almost, it’s open sourced and I use its PogoHelper the rest of the code is by me expect for the spawn function which allows you to execute commands as root. And they don’t have a license

**Comment by BenjaminHornbeck6** [comment]
I asked the developer of Pogo if I have permission to use the PogoHelper binary and if they respond with I don’t have permission to use it I’ll make this repo private until then it’ll be public
