### ISSUE TITLE
Violating Copyrights

### ISSUE THREAD

**Issue by pwnedcold** [BenjaminHornbeck6/lemonra1n#4]
![E13E157B-EE3B-4EAC-83A1-BC0C9844D992](https://user-images.githubusercontent.com/71401304/192115956-fa42e33b-c51f-48ee-b62f-a1b2503835ab.jpeg)
![4F2F549A-B6EB-48CD-9C76-3EF087704BE2](https://user-images.githubusercontent.com/71401304/192115957-735eb6ae-a709-47b0-b72a-6bcde469a4fb.jpeg)

get over it boy you are not allowed

**Comment by elihwyma** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by BenjaminHornbeck6** [comment]
Ok check the hashes on pogos binary then check my binary.

**Comment by mineek** [comment]
u serious?

**Comment by BenjaminHornbeck6** [comment]
Amy should I remove my loader app? Even though it’s completely remade besides PogoHelper and sawn root function

**Comment by BenjaminHornbeck6** [comment]
![87E6068F-2A9E-47FE-907B-C9CFB6E24B30](https://user-images.githubusercontent.com/98632439/192116387-6a407d29-a413-4de7-bdab-45d91771bcdf.png)
![796E111D-1E6D-43DE-B2C8-0E0051458B5E](https://user-images.githubusercontent.com/98632439/192116392-07077682-dbe6-4f2c-b7a4-9d95e990ee02.png)
Mines in swift ui the other thing is in ui kit. I will remove this if Amy wants it removed

**Comment by BenjaminHornbeck6** [comment]
Also I did credit Amy for the PogoHelper code

**Comment by elihwyma** [comment]
> ![87E6068F-2A9E-47FE-907B-C9CFB6E24B30](https://user-images.githubusercontent.com/98632439/192116387-6a407d29-a413-4de7-bdab-45d91771bcdf.png) ![796E111D-1E6D-43DE-B2C8-0E0051458B5E](https://user-images.githubusercontent.com/98632439/192116392-07077682-dbe6-4f2c-b7a4-9d95e990ee02.png) Mines in swift ui the other thing is in ui kit. I will remove this if Amy wants it removed

Not quite sure how checkra1n team would feel if you 1:1 copied their UI

**Comment by mineek** [comment]
> Also I did credit Amy for the PogoHelper code

so? like not trynna be mean or anything but like crediting is not enough if ur not complying with license.

**Comment by donato-fiore** [comment]
🤡

**Comment by BenjaminHornbeck6** [comment]
I removed it, I also DM Amy I’m Twitter for permission and I didn’t get any response

**Comment by elihwyma** [comment]
So did you assume that no response meant it was ok to reupload my work?

**Comment by BenjaminHornbeck6** [comment]
Did Amy copyright Pogo? If so how come I didn’t see any license on the repo

**Comment by mineek** [comment]
:fr:

**Comment by elihwyma** [comment]
> Did Amy copyright Pogo? If so how come I didn’t see any license on the repo

No license means its fully coprighted you sped

**Comment by elihwyma** [comment]
> > Did Amy copyright Pogo? If so how come I didn’t see any license on the repo
> 
> No license means its fully coprighted you sped

For further information please refer to my previous comment which you quite happily ignored: https://github.com/BenjaminHornbeck6/lemonra1n/issues/4#issuecomment-1257054034

**Comment by BenjaminHornbeck6** [comment]
I know. I’m sorry for redistributing your work even though it you call it dog shit I took it down really the only code it has is from Pogo is PogoHelper

**Comment by BenjaminHornbeck6** [comment]
Oh and your spawn function

**Comment by ma1ted** [comment]
> Ok check the hashes on pogos binary then check my binary.

Hahaha you clown

**Comment by elihwyma** [comment]
> I know. I’m sorry for redistributing your work even though it you call it dog shit I took it down really the only code it has is from Pogo is PogoHelper

Doesn't matter what I call it, its still my copyright. You aren't allowed to use any elements from the code without explicit permission from the copyright holder.

**Comment by donato-fiore** [comment]
there's nothing you can do to make this better for yourself, just delete the repo and move on with your day and stop stealing code

**Comment by BenjaminHornbeck6** [comment]
I didn’t even know you copyrighted it. I’m not good with copyright stuff

**Comment by elihwyma** [comment]
Heres a top tip: Before you reupload someones code maybe check if thats illegal or not!
